/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: LEASED,IN_STORAGE,DISCARDED,ON_REPAIR,MISSING
 */

@JsonClass(generateAdapter = false)
enum class DeviceStatus(val value: kotlin.String) {

    @Json(name = "LEASED")
    LEASED("LEASED"),

    @Json(name = "IN_STORAGE")
    IN_STORAGE("IN_STORAGE"),

    @Json(name = "DISCARDED")
    DISCARDED("DISCARDED"),

    @Json(name = "ON_REPAIR")
    ON_REPAIR("ON_REPAIR"),

    @Json(name = "MISSING")
    MISSING("MISSING");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DeviceStatus) "$data" else null

        /**
         * Returns a valid [DeviceStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DeviceStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

