/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model

import com.squareup.moshi.Json

/**
 * 
 *
 * @param inventoryId 
 * @param type 
 * @param manufacturer 
 * @param serialNumber 
 * @param assetName 
 * @param supplier 
 * @param invoiceNumber 
 * @param shipmentDateBegin 
 * @param shipmentDateEnd 
 * @param warrantyBegin 
 * @param warrantyEnd 
 * @param condition 
 * @param status 
 * @param leaseStartDate 
 * @param leaseEndDate 
 * @param userName 
 * @param site 
 * @param location 
 * @param note 
 * @param tags 
 * @param isTestDevice 
 */


data class DeviceSearchRequest (

    @Json(name = "inventoryId")
    val inventoryId: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "type")
    val type: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "manufacturer")
    val manufacturer: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "serialNumber")
    val serialNumber: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "assetName")
    val assetName: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "supplier")
    val supplier: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "invoiceNumber")
    val invoiceNumber: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "shipmentDateBegin")
    val shipmentDateBegin: java.time.LocalDate? = null,

    @Json(name = "shipmentDateEnd")
    val shipmentDateEnd: java.time.LocalDate? = null,

    @Json(name = "warrantyBegin")
    val warrantyBegin: java.time.LocalDate? = null,

    @Json(name = "warrantyEnd")
    val warrantyEnd: java.time.LocalDate? = null,

    @Json(name = "condition")
    val condition: kotlin.collections.List<DeviceCondition>? = null,

    @Json(name = "status")
    val status: kotlin.collections.List<DeviceStatus>? = null,

    @Json(name = "leaseStartDate")
    val leaseStartDate: java.time.LocalDate? = null,

    @Json(name = "leaseEndDate")
    val leaseEndDate: java.time.LocalDate? = null,

    @Json(name = "userName")
    val userName: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "site")
    val site: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "location")
    val location: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "note")
    val note: kotlin.String? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<Tag>? = null,

    @Json(name = "isTestDevice")
    val isTestDevice: kotlin.Boolean? = null

) {


}

