/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param errorCode 
 * @param errorKey 
 * @param defaultErrorMessage 
 * @param params 
 */


data class Error (

    @Json(name = "errorCode")
    val errorCode: java.math.BigDecimal,

    @Json(name = "errorKey")
    val errorKey: kotlin.String,

    @Json(name = "defaultErrorMessage")
    val defaultErrorMessage: kotlin.String,

    @Json(name = "params")
    val params: kotlin.collections.List<kotlin.Any>

) {


}

