/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Error

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param traceId 
 * @param errors 
 */


data class ErrorResponse (

    @Json(name = "traceId")
    val traceId: kotlin.String,

    @Json(name = "errors")
    val errors: kotlin.collections.List<Error>

) {


}

