/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param manufacturer Name of the manufacturer
 * @param assets 
 */


data class GetTestDeviceManufacturersResponse (

    /* Name of the manufacturer */
    @Json(name = "manufacturer")
    val manufacturer: kotlin.String,

    @Json(name = "assets")
    val assets: kotlin.collections.List<kotlin.String>

) {


}

