/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param timestamp 
 * @param action 
 * @param modifierEmail 
 * @param description 
 * @param actorEmail 
 */


data class HistoryResponse (

    @Json(name = "timestamp")
    val timestamp: java.time.LocalDate,

    @Json(name = "action")
    val action: kotlin.String,

    @Json(name = "modifierEmail")
    val modifierEmail: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "actorEmail")
    val actorEmail: kotlin.String? = null

) {


}

