/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param timestamp 
 * @param note 
 */


data class HistoryNoteRequest (

    @Json(name = "timestamp")
    val timestamp: java.time.LocalDate,

    @Json(name = "note")
    val note: kotlin.String

) {


}

