/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param deviceId 
 * @param startDate 
 * @param endDate 
 * @param userId 
 * @param userName 
 */


data class Leasing (

    @Json(name = "deviceId")
    val deviceId: java.util.UUID? = null,

    @Json(name = "startDate")
    val startDate: java.time.LocalDate? = null,

    @Json(name = "endDate")
    val endDate: java.time.LocalDate? = null,

    @Json(name = "userId")
    val userId: java.util.UUID? = null,

    @Json(name = "userName")
    val userName: kotlin.String? = null

) {


}

