/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param leaseId 
 * @param inventoryId 
 * @param startDate 
 * @param userId 
 * @param userName 
 * @param endDate 
 */


data class Leasing (

    @Json(name = "leaseId")
    val leaseId: java.util.UUID,

    @Json(name = "inventoryId")
    val inventoryId: kotlin.String,

    @Json(name = "startDate")
    val startDate: java.time.LocalDate,

    @Json(name = "userId")
    val userId: java.util.UUID,

    @Json(name = "userName")
    val userName: kotlin.String,

    @Json(name = "endDate")
    val endDate: java.time.LocalDate? = null

) {


}

