/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model

import com.zenitech.imaapp.data.model.DeviceStatus

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param assetName 
 * @param inventoryId 
 * @param manufacturer 
 * @param type 
 * @param dateOfHandover 
 * @param status 
 */


data class MyDeviceResponse (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "assetName")
    val assetName: kotlin.String,

    @Json(name = "inventoryId")
    val inventoryId: kotlin.String,

    @Json(name = "manufacturer")
    val manufacturer: kotlin.String,

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "dateOfHandover")
    val dateOfHandover: java.time.LocalDate,

    @Json(name = "status")
    val status: DeviceStatus

) {


}

