/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param number 
 * @param propertySize 
 * @param numberOfElements 
 * @param totalElements 
 * @param totalPages 
 * @param isFirst 
 * @param isLast 
 * @param hasNext 
 * @param hasPrevious 
 */


data class Page (

    @Json(name = "number")
    val number: kotlin.Int,

    @Json(name = "size")
    val propertySize: kotlin.Int,

    @Json(name = "numberOfElements")
    val numberOfElements: kotlin.Int,

    @Json(name = "totalElements")
    val totalElements: kotlin.Long,

    @Json(name = "totalPages")
    val totalPages: kotlin.Int,

    @Json(name = "isFirst")
    val isFirst: kotlin.Boolean,

    @Json(name = "isLast")
    val isLast: kotlin.Boolean,

    @Json(name = "hasNext")
    val hasNext: kotlin.Boolean,

    @Json(name = "hasPrevious")
    val hasPrevious: kotlin.Boolean

) {


}

