/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param word 
 * @param pdf 
 */


data class ReportResponse (

    @Json(name = "word")
    val word: kotlin.ByteArray? = null,

    @Json(name = "pdf")
    val pdf: kotlin.ByteArray? = null

) {


}

