/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: WORD,PDF,BOTH
 */

@JsonClass(generateAdapter = false)
enum class ReportFormat(val value: kotlin.String) {

    @Json(name = "WORD")
    WORD("WORD"),

    @Json(name = "PDF")
    PDF("PDF"),

    @Json(name = "BOTH")
    BOTH("BOTH");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ReportFormat) "$data" else null

        /**
         * Returns a valid [ReportFormat] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ReportFormat? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

