/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RequestStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestId 
 * @param manufacturer 
 * @param asset 
 * @param startDate 
 * @param endDate 
 * @param note 
 * @param status 
 */


data class TestDeviceRequest (

    @Json(name = "requestId")
    val requestId: java.util.UUID,

    @Json(name = "manufacturer")
    val manufacturer: kotlin.String,

    @Json(name = "asset")
    val asset: kotlin.String,

    @Json(name = "startDate")
    val startDate: java.time.LocalDate,

    @Json(name = "endDate")
    val endDate: java.time.LocalDate,

    @Json(name = "note")
    val note: kotlin.String,

    @Json(name = "status")
    val status: RequestStatus

) {


}

