/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.zenitech.imaapp.data.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param username 
 */


data class UserSearchRequest (

    @Json(name = "username")
    val username: kotlin.String? = null

) {


}

